## Gauss Jacobi's method

### Iteration formula:
      xi = -inv(D)*(Upper+Lower)*x0+inv(D)*B
  

In [1]:
% define co-effcient matrix and variable matrix
A = [10 -2 1; -2 10 -2; -2 -5 10] % co-efficient matrix
B = [5; 26; -7] % variable matrix

A =

   10   -2    1
   -2   10   -2
   -2   -5   10

B =

    5
   26
   -7



In [2]:
% access the length of co-efficient matrix
n = length(A)

n =  3


In [3]:
% get the diagonal of co-efficient matrix
D = diag(A)

D =

   10
   10
   10



In [4]:
% create a diagonal matrix with this diagonal
D = diag(D)

D =

Diagonal Matrix

   10    0    0
    0   10    0
    0    0   10



In [5]:
% create the upper triangle matrix on n*n formation
Upper = triu(A,1)

Upper =

   0  -2   1
   0   0  -2
   0   0   0



In [6]:
% create the lower triangle matrix on n*n formation
Lower = tril(A,-1)

Lower =

   0   0   0
  -2   0   0
  -2  -5   0



In [7]:
% initial iteration value
x0 = zeros(n,1)

x0 =

   0
   0
   0



In [8]:
%create first iteration x1 = 1
x1=1;

In [9]:
% xi for updating iteration value
xi = x0 % initially x0 as initial value

xi =

   0
   0
   0



In [10]:
% iteration : accepted error 10^-6
max_error = 10^-8;
while(abs(x1-xi) > max_error)
    x1 = -inv(D)*(Upper+Lower)*x0+inv(D)*B;
    xi=x0;
    x0=x1;
end

In [11]:
x1 % display the approximate value

x1 =

   1.00000
   3.00000
   1.00000




## Gause Seidel's upgration
  ### Formula:
      xi = -inv(D+Lower)*Upper*x0+inv(D+Lower)*B

In [12]:
% define co-effcient matrix and variable matrix
A = [10 -2 1; -2 10 -2; -2 -5 10] % co-efficient matrix
B = [5; 26; -7] % variable matrix

A =

   10   -2    1
   -2   10   -2
   -2   -5   10

B =

    5
   26
   -7



In [13]:
n = length(A)
x0 = zeros(n,1);
x1 = 1;
xi = x0;

n =  3


In [14]:
while(abs(x1-xi) > 10^-6)
    x1 = -inv(D+Lower)*Upper*x0+inv(D+Lower)*B;
    xi=x0;
    x0=x1;
end
x1

x1 =

   1.00000
   3.00000
   1.00000



### Source Code:
  * ### [Jacobi](octave/gauss_jacobi.m)
  * ### [Seidel](octave/gauss_seidel.m)